services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    ports:
      - "9090:9090"
    volumes:
      - ./data:/etc/linkding/data
    environment:
      - LD_SUPERUSER_NAME=admin
      - LD_SUPERUSER_PASSWORD=${LINKDING_PASSWORD}
    restart: unless-stopped
    networks:
      - infra-net

networks:
  infra-net :
    external: true
